# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Interface_Measurement.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_F_Kugler_Bench(object):
    def setupUi(self, F_Kugler_Bench):
        F_Kugler_Bench.setObjectName(_fromUtf8("F_Kugler_Bench"))
        F_Kugler_Bench.resize(1027, 906)
        F_Kugler_Bench.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.tabWidget = QtGui.QTabWidget(F_Kugler_Bench)
        self.tabWidget.setGeometry(QtCore.QRect(10, 10, 1010, 890))
        self.tabWidget.setTabPosition(QtGui.QTabWidget.North)
        self.tabWidget.setTabShape(QtGui.QTabWidget.Triangular)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.groupBox_3 = QtGui.QGroupBox(self.tab)
        self.groupBox_3.setGeometry(QtCore.QRect(40, 10, 200, 320))
        self.groupBox_3.setTitle(_fromUtf8(""))
        self.groupBox_3.setObjectName(_fromUtf8("groupBox_3"))
        self.label_128 = QtGui.QLabel(self.groupBox_3)
        self.label_128.setGeometry(QtCore.QRect(20, 20, 155, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_128.setFont(font)
        self.label_128.setAlignment(QtCore.Qt.AlignCenter)
        self.label_128.setObjectName(_fromUtf8("label_128"))
        self.label_4 = QtGui.QLabel(self.groupBox_3)
        self.label_4.setGeometry(QtCore.QRect(10, 90, 180, 57))
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Interface/3458a.png")))
        self.label_4.setScaledContents(False)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.splitter = QtGui.QSplitter(self.groupBox_3)
        self.splitter.setGeometry(QtCore.QRect(10, 170, 180, 120))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.layoutWidget = QtGui.QWidget(self.splitter)
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setSpacing(15)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.cb_DMM_X = QtGui.QCheckBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_DMM_X.setFont(font)
        self.cb_DMM_X.setObjectName(_fromUtf8("cb_DMM_X"))
        self.horizontalLayout.addWidget(self.cb_DMM_X)
        self.sb_DMM_X_address = QtGui.QSpinBox(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_DMM_X_address.setFont(font)
        self.sb_DMM_X_address.setSuffix(_fromUtf8(""))
        self.sb_DMM_X_address.setObjectName(_fromUtf8("sb_DMM_X_address"))
        self.horizontalLayout.addWidget(self.sb_DMM_X_address)
        self.horizontalLayout.setStretch(0, 1)
        self.layoutWidget_2 = QtGui.QWidget(self.splitter)
        self.layoutWidget_2.setObjectName(_fromUtf8("layoutWidget_2"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setSpacing(15)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cb_DMM_Y = QtGui.QCheckBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_DMM_Y.setFont(font)
        self.cb_DMM_Y.setObjectName(_fromUtf8("cb_DMM_Y"))
        self.horizontalLayout_2.addWidget(self.cb_DMM_Y)
        self.sb_DMM_Y_address = QtGui.QSpinBox(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_DMM_Y_address.setFont(font)
        self.sb_DMM_Y_address.setObjectName(_fromUtf8("sb_DMM_Y_address"))
        self.horizontalLayout_2.addWidget(self.sb_DMM_Y_address)
        self.horizontalLayout_2.setStretch(0, 1)
        self.layoutWidget_3 = QtGui.QWidget(self.splitter)
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.layoutWidget_3)
        self.horizontalLayout_3.setSpacing(15)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.cb_DMM_Z = QtGui.QCheckBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_DMM_Z.setFont(font)
        self.cb_DMM_Z.setObjectName(_fromUtf8("cb_DMM_Z"))
        self.horizontalLayout_3.addWidget(self.cb_DMM_Z)
        self.sb_DMM_Z_address = QtGui.QSpinBox(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_DMM_Z_address.setFont(font)
        self.sb_DMM_Z_address.setObjectName(_fromUtf8("sb_DMM_Z_address"))
        self.horizontalLayout_3.addWidget(self.sb_DMM_Z_address)
        self.horizontalLayout_3.setStretch(0, 1)
        self.groupBox_4 = QtGui.QGroupBox(self.tab)
        self.groupBox_4.setGeometry(QtCore.QRect(280, 10, 200, 210))
        self.groupBox_4.setTitle(_fromUtf8(""))
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.label_5 = QtGui.QLabel(self.groupBox_4)
        self.label_5.setGeometry(QtCore.QRect(16, 90, 170, 60))
        self.label_5.setText(_fromUtf8(""))
        self.label_5.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Interface/pmac.jpg")))
        self.label_5.setScaledContents(True)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.label_130 = QtGui.QLabel(self.groupBox_4)
        self.label_130.setGeometry(QtCore.QRect(50, 20, 92, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_130.setFont(font)
        self.label_130.setAlignment(QtCore.Qt.AlignCenter)
        self.label_130.setObjectName(_fromUtf8("label_130"))
        self.cb_PMAC_enable = QtGui.QCheckBox(self.groupBox_4)
        self.cb_PMAC_enable.setGeometry(QtCore.QRect(11, 179, 180, 16))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_PMAC_enable.setFont(font)
        self.cb_PMAC_enable.setObjectName(_fromUtf8("cb_PMAC_enable"))
        self.groupBox_5 = QtGui.QGroupBox(self.tab)
        self.groupBox_5.setGeometry(QtCore.QRect(520, 10, 200, 210))
        self.groupBox_5.setTitle(_fromUtf8(""))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.label_129 = QtGui.QLabel(self.groupBox_5)
        self.label_129.setGeometry(QtCore.QRect(10, 20, 180, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_129.setFont(font)
        self.label_129.setAlignment(QtCore.Qt.AlignCenter)
        self.label_129.setObjectName(_fromUtf8("label_129"))
        self.label_6 = QtGui.QLabel(self.groupBox_5)
        self.label_6.setGeometry(QtCore.QRect(10, 80, 180, 70))
        self.label_6.setText(_fromUtf8(""))
        self.label_6.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Interface/34970A.jpg")))
        self.label_6.setScaledContents(True)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.cb_Multichannel_enable = QtGui.QCheckBox(self.groupBox_5)
        self.cb_Multichannel_enable.setGeometry(QtCore.QRect(11, 173, 80, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_Multichannel_enable.setFont(font)
        self.cb_Multichannel_enable.setObjectName(_fromUtf8("cb_Multichannel_enable"))
        self.sb_Multichannel_address = QtGui.QSpinBox(self.groupBox_5)
        self.sb_Multichannel_address.setGeometry(QtCore.QRect(120, 174, 60, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_Multichannel_address.setFont(font)
        self.sb_Multichannel_address.setSuffix(_fromUtf8(""))
        self.sb_Multichannel_address.setObjectName(_fromUtf8("sb_Multichannel_address"))
        self.groupBox_6 = QtGui.QGroupBox(self.tab)
        self.groupBox_6.setEnabled(False)
        self.groupBox_6.setGeometry(QtCore.QRect(760, 10, 200, 210))
        self.groupBox_6.setTitle(_fromUtf8(""))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.label_131 = QtGui.QLabel(self.groupBox_6)
        self.label_131.setGeometry(QtCore.QRect(10, 20, 180, 46))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_131.setFont(font)
        self.label_131.setAlignment(QtCore.Qt.AlignCenter)
        self.label_131.setObjectName(_fromUtf8("label_131"))
        self.label_7 = QtGui.QLabel(self.groupBox_6)
        self.label_7.setGeometry(QtCore.QRect(46, 60, 100, 100))
        self.label_7.setText(_fromUtf8(""))
        self.label_7.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Interface/elcomat.jpg")))
        self.label_7.setScaledContents(True)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.cb_Autocolimator_port = QtGui.QComboBox(self.groupBox_6)
        self.cb_Autocolimator_port.setGeometry(QtCore.QRect(102, 174, 87, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_Autocolimator_port.setFont(font)
        self.cb_Autocolimator_port.setObjectName(_fromUtf8("cb_Autocolimator_port"))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_port.addItem(_fromUtf8(""))
        self.cb_Autocolimator_enable = QtGui.QCheckBox(self.groupBox_6)
        self.cb_Autocolimator_enable.setGeometry(QtCore.QRect(11, 172, 80, 27))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_Autocolimator_enable.setFont(font)
        self.cb_Autocolimator_enable.setObjectName(_fromUtf8("cb_Autocolimator_enable"))
        self.groupBox_7 = QtGui.QGroupBox(self.tab)
        self.groupBox_7.setGeometry(QtCore.QRect(280, 220, 440, 110))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_7.setFont(font)
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.le_filenameconfig = QtGui.QLineEdit(self.groupBox_7)
        self.le_filenameconfig.setGeometry(QtCore.QRect(88, 32, 330, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.le_filenameconfig.setFont(font)
        self.le_filenameconfig.setStyleSheet(_fromUtf8("font: 8pt \"MS Shell Dlg 2\";"))
        self.le_filenameconfig.setText(_fromUtf8(""))
        self.le_filenameconfig.setReadOnly(True)
        self.le_filenameconfig.setObjectName(_fromUtf8("le_filenameconfig"))
        self.label_3 = QtGui.QLabel(self.groupBox_7)
        self.label_3.setGeometry(QtCore.QRect(20, 33, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.pb_saveconfigfile = QtGui.QPushButton(self.groupBox_7)
        self.pb_saveconfigfile.setGeometry(QtCore.QRect(230, 70, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_saveconfigfile.setFont(font)
        self.pb_saveconfigfile.setObjectName(_fromUtf8("pb_saveconfigfile"))
        self.pb_loadconfigfile = QtGui.QPushButton(self.groupBox_7)
        self.pb_loadconfigfile.setGeometry(QtCore.QRect(40, 70, 170, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_loadconfigfile.setFont(font)
        self.pb_loadconfigfile.setObjectName(_fromUtf8("pb_loadconfigfile"))
        self.groupBox_8 = QtGui.QGroupBox(self.tab)
        self.groupBox_8.setGeometry(QtCore.QRect(760, 230, 200, 100))
        self.groupBox_8.setTitle(_fromUtf8(""))
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.pb_connectdevices = QtGui.QPushButton(self.groupBox_8)
        self.pb_connectdevices.setGeometry(QtCore.QRect(10, 10, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_connectdevices.setFont(font)
        self.pb_connectdevices.setObjectName(_fromUtf8("pb_connectdevices"))
        self.pb_disconnectdevices = QtGui.QPushButton(self.groupBox_8)
        self.pb_disconnectdevices.setGeometry(QtCore.QRect(10, 60, 180, 30))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.pb_disconnectdevices.setFont(font)
        self.pb_disconnectdevices.setObjectName(_fromUtf8("pb_disconnectdevices"))
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setGeometry(QtCore.QRect(150, 340, 670, 520))
        self.label_10.setText(_fromUtf8(""))
        self.label_10.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Interface/bench.PNG")))
        self.label_10.setScaledContents(True)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_motors = QtGui.QWidget()
        self.tab_motors.setObjectName(_fromUtf8("tab_motors"))
        self.label = QtGui.QLabel(self.tab_motors)
        self.label.setGeometry(QtCore.QRect(10, 10, 430, 330))
        self.label.setText(_fromUtf8(""))
        self.label.setPixmap(QtGui.QPixmap(_fromUtf8(":/Images/Interface/Coordinate_System.png")))
        self.label.setObjectName(_fromUtf8("label"))
        self.gb_axisreadings = QtGui.QGroupBox(self.tab_motors)
        self.gb_axisreadings.setGeometry(QtCore.QRect(780, 18, 210, 311))
        self.gb_axisreadings.setTitle(_fromUtf8(""))
        self.gb_axisreadings.setObjectName(_fromUtf8("gb_axisreadings"))
        self.gridLayout_4 = QtGui.QGridLayout(self.gb_axisreadings)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.label_23 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_4.addWidget(self.label_23, 0, 0, 1, 1)
        self.le_pos1 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos1.setFont(font)
        self.le_pos1.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos1.setReadOnly(True)
        self.le_pos1.setObjectName(_fromUtf8("le_pos1"))
        self.gridLayout_4.addWidget(self.le_pos1, 0, 1, 1, 1)
        self.label_120 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_120.setFont(font)
        self.label_120.setObjectName(_fromUtf8("label_120"))
        self.gridLayout_4.addWidget(self.label_120, 0, 2, 1, 1)
        self.label_24 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_4.addWidget(self.label_24, 1, 0, 1, 1)
        self.le_pos2 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos2.setFont(font)
        self.le_pos2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos2.setReadOnly(True)
        self.le_pos2.setObjectName(_fromUtf8("le_pos2"))
        self.gridLayout_4.addWidget(self.le_pos2, 1, 1, 1, 1)
        self.label_121 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_121.setFont(font)
        self.label_121.setObjectName(_fromUtf8("label_121"))
        self.gridLayout_4.addWidget(self.label_121, 1, 2, 1, 1)
        self.label_25 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_4.addWidget(self.label_25, 2, 0, 1, 1)
        self.le_pos3 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos3.setFont(font)
        self.le_pos3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos3.setReadOnly(True)
        self.le_pos3.setObjectName(_fromUtf8("le_pos3"))
        self.gridLayout_4.addWidget(self.le_pos3, 2, 1, 1, 1)
        self.label_122 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_122.setFont(font)
        self.label_122.setObjectName(_fromUtf8("label_122"))
        self.gridLayout_4.addWidget(self.label_122, 2, 2, 1, 1)
        self.label_26 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.gridLayout_4.addWidget(self.label_26, 3, 0, 1, 1)
        self.le_pos5 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos5.setFont(font)
        self.le_pos5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos5.setReadOnly(True)
        self.le_pos5.setObjectName(_fromUtf8("le_pos5"))
        self.gridLayout_4.addWidget(self.le_pos5, 3, 1, 1, 1)
        self.label_123 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_123.setFont(font)
        self.label_123.setObjectName(_fromUtf8("label_123"))
        self.gridLayout_4.addWidget(self.label_123, 3, 2, 1, 1)
        self.label_27 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_4.addWidget(self.label_27, 4, 0, 1, 1)
        self.le_pos6 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos6.setFont(font)
        self.le_pos6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos6.setReadOnly(True)
        self.le_pos6.setObjectName(_fromUtf8("le_pos6"))
        self.gridLayout_4.addWidget(self.le_pos6, 4, 1, 1, 1)
        self.label_124 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_124.setFont(font)
        self.label_124.setObjectName(_fromUtf8("label_124"))
        self.gridLayout_4.addWidget(self.label_124, 4, 2, 1, 1)
        self.label_28 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.gridLayout_4.addWidget(self.label_28, 5, 0, 1, 1)
        self.le_pos7 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos7.setFont(font)
        self.le_pos7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos7.setReadOnly(True)
        self.le_pos7.setObjectName(_fromUtf8("le_pos7"))
        self.gridLayout_4.addWidget(self.le_pos7, 5, 1, 1, 1)
        self.label_125 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_125.setFont(font)
        self.label_125.setObjectName(_fromUtf8("label_125"))
        self.gridLayout_4.addWidget(self.label_125, 5, 2, 1, 1)
        self.label_29 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.gridLayout_4.addWidget(self.label_29, 6, 0, 1, 1)
        self.le_pos8 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos8.setFont(font)
        self.le_pos8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos8.setReadOnly(True)
        self.le_pos8.setObjectName(_fromUtf8("le_pos8"))
        self.gridLayout_4.addWidget(self.le_pos8, 6, 1, 1, 1)
        self.label_126 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_126.setFont(font)
        self.label_126.setObjectName(_fromUtf8("label_126"))
        self.gridLayout_4.addWidget(self.label_126, 6, 2, 1, 1)
        self.label_30 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.gridLayout_4.addWidget(self.label_30, 7, 0, 1, 1)
        self.le_pos9 = QtGui.QLineEdit(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos9.setFont(font)
        self.le_pos9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos9.setReadOnly(True)
        self.le_pos9.setObjectName(_fromUtf8("le_pos9"))
        self.gridLayout_4.addWidget(self.le_pos9, 7, 1, 1, 1)
        self.label_127 = QtGui.QLabel(self.gb_axisreadings)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_127.setFont(font)
        self.label_127.setObjectName(_fromUtf8("label_127"))
        self.gridLayout_4.addWidget(self.label_127, 7, 2, 1, 1)
        self.tb_Motors_main = QtGui.QToolBox(self.tab_motors)
        self.tb_Motors_main.setGeometry(QtCore.QRect(440, 50, 330, 220))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.tb_Motors_main.setFont(font)
        self.tb_Motors_main.setObjectName(_fromUtf8("tb_Motors_main"))
        self.tbmotors_homming = QtGui.QWidget()
        self.tbmotors_homming.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.tbmotors_homming.setObjectName(_fromUtf8("tbmotors_homming"))
        self.groupBox_9 = QtGui.QGroupBox(self.tbmotors_homming)
        self.groupBox_9.setGeometry(QtCore.QRect(0, 0, 330, 160))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.groupBox_9.setFont(font)
        self.groupBox_9.setObjectName(_fromUtf8("groupBox_9"))
        self.pb_starthomming = QtGui.QPushButton(self.groupBox_9)
        self.pb_starthomming.setGeometry(QtCore.QRect(20, 120, 290, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_starthomming.setFont(font)
        self.pb_starthomming.setObjectName(_fromUtf8("pb_starthomming"))
        self.layoutWidget1 = QtGui.QWidget(self.groupBox_9)
        self.layoutWidget1.setGeometry(QtCore.QRect(20, 20, 290, 100))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.gridLayout_5 = QtGui.QGridLayout(self.layoutWidget1)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.cb_homming1 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming1.setFont(font)
        self.cb_homming1.setObjectName(_fromUtf8("cb_homming1"))
        self.gridLayout_5.addWidget(self.cb_homming1, 0, 0, 1, 1)
        self.cb_homming5 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming5.setFont(font)
        self.cb_homming5.setObjectName(_fromUtf8("cb_homming5"))
        self.gridLayout_5.addWidget(self.cb_homming5, 0, 1, 1, 1)
        self.cb_homming8 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming8.setFont(font)
        self.cb_homming8.setObjectName(_fromUtf8("cb_homming8"))
        self.gridLayout_5.addWidget(self.cb_homming8, 0, 2, 1, 1)
        self.cb_homming2 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming2.setFont(font)
        self.cb_homming2.setObjectName(_fromUtf8("cb_homming2"))
        self.gridLayout_5.addWidget(self.cb_homming2, 1, 0, 1, 1)
        self.cb_homming6 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming6.setFont(font)
        self.cb_homming6.setObjectName(_fromUtf8("cb_homming6"))
        self.gridLayout_5.addWidget(self.cb_homming6, 1, 1, 1, 1)
        self.cb_homming9 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming9.setFont(font)
        self.cb_homming9.setObjectName(_fromUtf8("cb_homming9"))
        self.gridLayout_5.addWidget(self.cb_homming9, 1, 2, 1, 1)
        self.cb_homming3 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming3.setFont(font)
        self.cb_homming3.setObjectName(_fromUtf8("cb_homming3"))
        self.gridLayout_5.addWidget(self.cb_homming3, 2, 0, 1, 1)
        self.cb_homming7 = QtGui.QCheckBox(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cb_homming7.setFont(font)
        self.cb_homming7.setObjectName(_fromUtf8("cb_homming7"))
        self.gridLayout_5.addWidget(self.cb_homming7, 2, 1, 1, 1)
        self.tb_Motors_main.addItem(self.tbmotors_homming, _fromUtf8(""))
        self.tbmotors_movements = QtGui.QWidget()
        self.tbmotors_movements.setGeometry(QtCore.QRect(0, 0, 100, 30))
        self.tbmotors_movements.setObjectName(_fromUtf8("tbmotors_movements"))
        self.gb_axismovement = QtGui.QGroupBox(self.tbmotors_movements)
        self.gb_axismovement.setGeometry(QtCore.QRect(0, 0, 330, 120))
        self.gb_axismovement.setTitle(_fromUtf8(""))
        self.gb_axismovement.setObjectName(_fromUtf8("gb_axismovement"))
        self.layoutWidget2 = QtGui.QWidget(self.gb_axismovement)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 8, 317, 100))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.verticalLayout = QtGui.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.label_21 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.horizontalLayout_4.addWidget(self.label_21)
        self.le_velocity = QtGui.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        font.setWeight(50)
        self.le_velocity.setFont(font)
        self.le_velocity.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_velocity.setObjectName(_fromUtf8("le_velocity"))
        self.horizontalLayout_4.addWidget(self.le_velocity)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_2 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.horizontalLayout_6.addWidget(self.label_2)
        self.cb_selectaxis = QtGui.QComboBox(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.cb_selectaxis.setFont(font)
        self.cb_selectaxis.setObjectName(_fromUtf8("cb_selectaxis"))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.cb_selectaxis.addItem(_fromUtf8(""))
        self.horizontalLayout_6.addWidget(self.cb_selectaxis)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.label_20 = QtGui.QLabel(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.horizontalLayout_5.addWidget(self.label_20)
        self.le_targetposition = QtGui.QLineEdit(self.layoutWidget2)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.le_targetposition.setFont(font)
        self.le_targetposition.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_targetposition.setObjectName(_fromUtf8("le_targetposition"))
        self.horizontalLayout_5.addWidget(self.le_targetposition)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        self.groupBox = QtGui.QGroupBox(self.tbmotors_movements)
        self.groupBox.setGeometry(QtCore.QRect(0, 118, 330, 43))
        self.groupBox.setTitle(_fromUtf8(""))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.pb_stopmotor = QtGui.QPushButton(self.groupBox)
        self.pb_stopmotor.setGeometry(QtCore.QRect(168, 7, 152, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_stopmotor.setFont(font)
        self.pb_stopmotor.setObjectName(_fromUtf8("pb_stopmotor"))
        self.pb_movetotarget = QtGui.QPushButton(self.groupBox)
        self.pb_movetotarget.setGeometry(QtCore.QRect(10, 7, 152, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_movetotarget.setFont(font)
        self.pb_movetotarget.setObjectName(_fromUtf8("pb_movetotarget"))
        self.tb_Motors_main.addItem(self.tbmotors_movements, _fromUtf8(""))
        self.groupBox_2 = QtGui.QGroupBox(self.tab_motors)
        self.groupBox_2.setGeometry(QtCore.QRect(440, 280, 331, 47))
        self.groupBox_2.setTitle(_fromUtf8(""))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_3 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.pb_killallmotors = QtGui.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_killallmotors.setFont(font)
        self.pb_killallmotors.setObjectName(_fromUtf8("pb_killallmotors"))
        self.gridLayout_3.addWidget(self.pb_killallmotors, 0, 1, 1, 1)
        self.pb_stopallmotors = QtGui.QPushButton(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_stopallmotors.setFont(font)
        self.pb_stopallmotors.setObjectName(_fromUtf8("pb_stopallmotors"))
        self.gridLayout_3.addWidget(self.pb_stopallmotors, 0, 0, 1, 1)
        self.pb_activatebench = QtGui.QPushButton(self.tab_motors)
        self.pb_activatebench.setGeometry(QtCore.QRect(440, 20, 330, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_activatebench.setFont(font)
        self.pb_activatebench.setObjectName(_fromUtf8("pb_activatebench"))
        self.tabWidget.addTab(self.tab_motors, _fromUtf8(""))
        self.tab_measurement = QtGui.QWidget()
        self.tab_measurement.setObjectName(_fromUtf8("tab_measurement"))
        self.gbMedidas = QtGui.QGroupBox(self.tab_measurement)
        self.gbMedidas.setGeometry(QtCore.QRect(10, 10, 990, 320))
        self.gbMedidas.setTitle(_fromUtf8(""))
        self.gbMedidas.setObjectName(_fromUtf8("gbMedidas"))
        self.groupBox_10 = QtGui.QGroupBox(self.gbMedidas)
        self.groupBox_10.setGeometry(QtCore.QRect(10, 120, 270, 70))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_10.setFont(font)
        self.groupBox_10.setObjectName(_fromUtf8("groupBox_10"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_10)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.cb_Hall_X_enable = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_Hall_X_enable.setFont(font)
        self.cb_Hall_X_enable.setChecked(True)
        self.cb_Hall_X_enable.setObjectName(_fromUtf8("cb_Hall_X_enable"))
        self.gridLayout_11.addWidget(self.cb_Hall_X_enable, 0, 0, 1, 1)
        self.cb_Hall_Y_enable = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_Hall_Y_enable.setFont(font)
        self.cb_Hall_Y_enable.setChecked(True)
        self.cb_Hall_Y_enable.setObjectName(_fromUtf8("cb_Hall_Y_enable"))
        self.gridLayout_11.addWidget(self.cb_Hall_Y_enable, 0, 1, 1, 1)
        self.cb_Hall_Z_enable = QtGui.QCheckBox(self.groupBox_10)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_Hall_Z_enable.setFont(font)
        self.cb_Hall_Z_enable.setChecked(True)
        self.cb_Hall_Z_enable.setObjectName(_fromUtf8("cb_Hall_Z_enable"))
        self.gridLayout_11.addWidget(self.cb_Hall_Z_enable, 0, 2, 1, 1)
        self.groupBox_11 = QtGui.QGroupBox(self.gbMedidas)
        self.groupBox_11.setGeometry(QtCore.QRect(10, 200, 270, 110))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_11.setFont(font)
        self.groupBox_11.setObjectName(_fromUtf8("groupBox_11"))
        self.label_22 = QtGui.QLabel(self.groupBox_11)
        self.label_22.setGeometry(QtCore.QRect(22, 33, 133, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.le_DMM_aper = QtGui.QLineEdit(self.groupBox_11)
        self.le_DMM_aper.setGeometry(QtCore.QRect(170, 32, 80, 25))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.le_DMM_aper.setFont(font)
        self.le_DMM_aper.setObjectName(_fromUtf8("le_DMM_aper"))
        self.cb_DMM_precision = QtGui.QComboBox(self.groupBox_11)
        self.cb_DMM_precision.setGeometry(QtCore.QRect(170, 70, 80, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.cb_DMM_precision.setFont(font)
        self.cb_DMM_precision.setObjectName(_fromUtf8("cb_DMM_precision"))
        self.cb_DMM_precision.addItem(_fromUtf8(""))
        self.cb_DMM_precision.addItem(_fromUtf8(""))
        self.label_32 = QtGui.QLabel(self.groupBox_11)
        self.label_32.setGeometry(QtCore.QRect(22, 74, 140, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_32.setFont(font)
        self.label_32.setObjectName(_fromUtf8("label_32"))
        self.groupBox_12 = QtGui.QGroupBox(self.gbMedidas)
        self.groupBox_12.setGeometry(QtCore.QRect(290, 10, 470, 190))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_12.setFont(font)
        self.groupBox_12.setObjectName(_fromUtf8("groupBox_12"))
        self.layoutWidget3 = QtGui.QWidget(self.groupBox_12)
        self.layoutWidget3.setGeometry(QtCore.QRect(10, 20, 450, 160))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.gridLayout_2 = QtGui.QGridLayout(self.layoutWidget3)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.label_35 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.gridLayout_2.addWidget(self.label_35, 2, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_2.addWidget(self.label_16, 0, 2, 1, 1)
        self.label_40 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.gridLayout_2.addWidget(self.label_40, 1, 1, 1, 1)
        self.label_17 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_17.setFont(font)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_2.addWidget(self.label_17, 0, 3, 1, 1)
        self.label_15 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_2.addWidget(self.label_15, 0, 4, 1, 1)
        self.label_36 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.gridLayout_2.addWidget(self.label_36, 4, 1, 1, 1)
        self.label_39 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.gridLayout_2.addWidget(self.label_39, 3, 1, 1, 1)
        self.le_axis1_end = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis1_end.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis1_end.setObjectName(_fromUtf8("le_axis1_end"))
        self.gridLayout_2.addWidget(self.le_axis1_end, 1, 3, 1, 1)
        self.le_axis5_start = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis5_start.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis5_start.setObjectName(_fromUtf8("le_axis5_start"))
        self.gridLayout_2.addWidget(self.le_axis5_start, 4, 2, 1, 1)
        self.le_axis3_start = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis3_start.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis3_start.setObjectName(_fromUtf8("le_axis3_start"))
        self.gridLayout_2.addWidget(self.le_axis3_start, 3, 2, 1, 1)
        self.le_axis5_step = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis5_step.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis5_step.setObjectName(_fromUtf8("le_axis5_step"))
        self.gridLayout_2.addWidget(self.le_axis5_step, 4, 4, 1, 1)
        self.le_axis3_end = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis3_end.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis3_end.setObjectName(_fromUtf8("le_axis3_end"))
        self.gridLayout_2.addWidget(self.le_axis3_end, 3, 3, 1, 1)
        self.le_axis1_step = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis1_step.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis1_step.setObjectName(_fromUtf8("le_axis1_step"))
        self.gridLayout_2.addWidget(self.le_axis1_step, 1, 4, 1, 1)
        self.rb_triggering_axis3 = QtGui.QRadioButton(self.layoutWidget3)
        self.rb_triggering_axis3.setText(_fromUtf8(""))
        self.rb_triggering_axis3.setObjectName(_fromUtf8("rb_triggering_axis3"))
        self.gridLayout_2.addWidget(self.rb_triggering_axis3, 3, 0, 1, 1)
        self.le_axis1_start = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis1_start.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis1_start.setObjectName(_fromUtf8("le_axis1_start"))
        self.gridLayout_2.addWidget(self.le_axis1_start, 1, 2, 1, 1)
        self.le_axis2_end = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis2_end.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis2_end.setObjectName(_fromUtf8("le_axis2_end"))
        self.gridLayout_2.addWidget(self.le_axis2_end, 2, 3, 1, 1)
        self.le_axis3_step = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis3_step.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis3_step.setObjectName(_fromUtf8("le_axis3_step"))
        self.gridLayout_2.addWidget(self.le_axis3_step, 3, 4, 1, 1)
        self.le_axis2_step = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis2_step.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis2_step.setObjectName(_fromUtf8("le_axis2_step"))
        self.gridLayout_2.addWidget(self.le_axis2_step, 2, 4, 1, 1)
        self.le_axis5_end = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis5_end.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis5_end.setObjectName(_fromUtf8("le_axis5_end"))
        self.gridLayout_2.addWidget(self.le_axis5_end, 4, 3, 1, 1)
        self.rb_triggering_axis2 = QtGui.QRadioButton(self.layoutWidget3)
        self.rb_triggering_axis2.setText(_fromUtf8(""))
        self.rb_triggering_axis2.setObjectName(_fromUtf8("rb_triggering_axis2"))
        self.gridLayout_2.addWidget(self.rb_triggering_axis2, 2, 0, 1, 1)
        self.le_axis2_start = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis2_start.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis2_start.setObjectName(_fromUtf8("le_axis2_start"))
        self.gridLayout_2.addWidget(self.le_axis2_start, 2, 2, 1, 1)
        self.rb_triggering_axis1 = QtGui.QRadioButton(self.layoutWidget3)
        self.rb_triggering_axis1.setEnabled(True)
        self.rb_triggering_axis1.setText(_fromUtf8(""))
        self.rb_triggering_axis1.setChecked(True)
        self.rb_triggering_axis1.setObjectName(_fromUtf8("rb_triggering_axis1"))
        self.gridLayout_2.addWidget(self.rb_triggering_axis1, 1, 0, 1, 1)
        self.le_axis1_vel = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis1_vel.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis1_vel.setObjectName(_fromUtf8("le_axis1_vel"))
        self.gridLayout_2.addWidget(self.le_axis1_vel, 1, 5, 1, 1)
        self.label_19 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_19.setFont(font)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.gridLayout_2.addWidget(self.label_19, 0, 5, 1, 1)
        self.le_axis3_vel = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis3_vel.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis3_vel.setObjectName(_fromUtf8("le_axis3_vel"))
        self.gridLayout_2.addWidget(self.le_axis3_vel, 3, 5, 1, 1)
        self.le_axis5_vel = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis5_vel.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis5_vel.setObjectName(_fromUtf8("le_axis5_vel"))
        self.gridLayout_2.addWidget(self.le_axis5_vel, 4, 5, 1, 1)
        self.le_axis2_vel = QtGui.QLineEdit(self.layoutWidget3)
        self.le_axis2_vel.setStyleSheet(_fromUtf8("font: 10pt \"MS Shell Dlg 2\";"))
        self.le_axis2_vel.setObjectName(_fromUtf8("le_axis2_vel"))
        self.gridLayout_2.addWidget(self.le_axis2_vel, 2, 5, 1, 1)
        self.label_18 = QtGui.QLabel(self.layoutWidget3)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_18.setFont(font)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_2.addWidget(self.label_18, 0, 0, 1, 2)
        self.gridLayout_2.setRowMinimumHeight(1, 25)
        self.gridLayout_2.setRowMinimumHeight(2, 25)
        self.gridLayout_2.setRowMinimumHeight(3, 25)
        self.gridLayout_2.setRowMinimumHeight(4, 25)
        self.groupBox_13 = QtGui.QGroupBox(self.gbMedidas)
        self.groupBox_13.setGeometry(QtCore.QRect(10, 10, 270, 104))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_13.setFont(font)
        self.groupBox_13.setObjectName(_fromUtf8("groupBox_13"))
        self.pb_savemeasurementfile = QtGui.QPushButton(self.groupBox_13)
        self.pb_savemeasurementfile.setGeometry(QtCore.QRect(140, 60, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_savemeasurementfile.setFont(font)
        self.pb_savemeasurementfile.setObjectName(_fromUtf8("pb_savemeasurementfile"))
        self.pb_loadmeasurementfile = QtGui.QPushButton(self.groupBox_13)
        self.pb_loadmeasurementfile.setGeometry(QtCore.QRect(20, 60, 110, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_loadmeasurementfile.setFont(font)
        self.pb_loadmeasurementfile.setObjectName(_fromUtf8("pb_loadmeasurementfile"))
        self.label_9 = QtGui.QLabel(self.groupBox_13)
        self.label_9.setGeometry(QtCore.QRect(12, 31, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.le_filenamemeasurement = QtGui.QLineEdit(self.groupBox_13)
        self.le_filenamemeasurement.setGeometry(QtCore.QRect(80, 30, 180, 20))
        self.le_filenamemeasurement.setStyleSheet(_fromUtf8("font: 8pt \"MS Shell Dlg 2\";"))
        self.le_filenamemeasurement.setReadOnly(True)
        self.le_filenamemeasurement.setObjectName(_fromUtf8("le_filenamemeasurement"))
        self.groupBox_14 = QtGui.QGroupBox(self.gbMedidas)
        self.groupBox_14.setGeometry(QtCore.QRect(290, 200, 470, 110))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_14.setFont(font)
        self.groupBox_14.setObjectName(_fromUtf8("groupBox_14"))
        self.pb_configure_measurement = QtGui.QPushButton(self.groupBox_14)
        self.pb_configure_measurement.setGeometry(QtCore.QRect(230, 25, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_configure_measurement.setFont(font)
        self.pb_configure_measurement.setObjectName(_fromUtf8("pb_configure_measurement"))
        self.pb_stop_measurements = QtGui.QPushButton(self.groupBox_14)
        self.pb_stop_measurements.setGeometry(QtCore.QRect(230, 65, 220, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pb_stop_measurements.setFont(font)
        self.pb_stop_measurements.setStyleSheet(_fromUtf8("color: rgb(255, 0, 0);"))
        self.pb_stop_measurements.setObjectName(_fromUtf8("pb_stop_measurements"))
        self.label_33 = QtGui.QLabel(self.groupBox_14)
        self.label_33.setGeometry(QtCore.QRect(42, 31, 150, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.sb_number_of_measurements = QtGui.QSpinBox(self.groupBox_14)
        self.sb_number_of_measurements.setGeometry(QtCore.QRect(40, 60, 70, 30))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.sb_number_of_measurements.setFont(font)
        self.sb_number_of_measurements.setMinimum(1)
        self.sb_number_of_measurements.setMaximum(1000000)
        self.sb_number_of_measurements.setObjectName(_fromUtf8("sb_number_of_measurements"))
        self.l_n_meas_status = QtGui.QLabel(self.groupBox_14)
        self.l_n_meas_status.setGeometry(QtCore.QRect(140, 66, 50, 19))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.l_n_meas_status.setFont(font)
        self.l_n_meas_status.setObjectName(_fromUtf8("l_n_meas_status"))
        self.gb_axisreadings_2 = QtGui.QGroupBox(self.gbMedidas)
        self.gb_axisreadings_2.setGeometry(QtCore.QRect(770, 20, 210, 290))
        self.gb_axisreadings_2.setTitle(_fromUtf8(""))
        self.gb_axisreadings_2.setObjectName(_fromUtf8("gb_axisreadings_2"))
        self.gridLayout_6 = QtGui.QGridLayout(self.gb_axisreadings_2)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.label_34 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.gridLayout_6.addWidget(self.label_34, 0, 0, 1, 1)
        self.le_pos1_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos1_2.setFont(font)
        self.le_pos1_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos1_2.setReadOnly(True)
        self.le_pos1_2.setObjectName(_fromUtf8("le_pos1_2"))
        self.gridLayout_6.addWidget(self.le_pos1_2, 0, 1, 1, 1)
        self.label_132 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_132.setFont(font)
        self.label_132.setObjectName(_fromUtf8("label_132"))
        self.gridLayout_6.addWidget(self.label_132, 0, 2, 1, 1)
        self.label_37 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.gridLayout_6.addWidget(self.label_37, 1, 0, 1, 1)
        self.le_pos2_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos2_2.setFont(font)
        self.le_pos2_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos2_2.setReadOnly(True)
        self.le_pos2_2.setObjectName(_fromUtf8("le_pos2_2"))
        self.gridLayout_6.addWidget(self.le_pos2_2, 1, 1, 1, 1)
        self.label_133 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_133.setFont(font)
        self.label_133.setObjectName(_fromUtf8("label_133"))
        self.gridLayout_6.addWidget(self.label_133, 1, 2, 1, 1)
        self.label_38 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.gridLayout_6.addWidget(self.label_38, 2, 0, 1, 1)
        self.le_pos3_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos3_2.setFont(font)
        self.le_pos3_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos3_2.setReadOnly(True)
        self.le_pos3_2.setObjectName(_fromUtf8("le_pos3_2"))
        self.gridLayout_6.addWidget(self.le_pos3_2, 2, 1, 1, 1)
        self.label_134 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_134.setFont(font)
        self.label_134.setObjectName(_fromUtf8("label_134"))
        self.gridLayout_6.addWidget(self.label_134, 2, 2, 1, 1)
        self.label_41 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_6.addWidget(self.label_41, 3, 0, 1, 1)
        self.le_pos5_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos5_2.setFont(font)
        self.le_pos5_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos5_2.setReadOnly(True)
        self.le_pos5_2.setObjectName(_fromUtf8("le_pos5_2"))
        self.gridLayout_6.addWidget(self.le_pos5_2, 3, 1, 1, 1)
        self.label_135 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_135.setFont(font)
        self.label_135.setObjectName(_fromUtf8("label_135"))
        self.gridLayout_6.addWidget(self.label_135, 3, 2, 1, 1)
        self.label_42 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.gridLayout_6.addWidget(self.label_42, 4, 0, 1, 1)
        self.le_pos6_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos6_2.setFont(font)
        self.le_pos6_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos6_2.setReadOnly(True)
        self.le_pos6_2.setObjectName(_fromUtf8("le_pos6_2"))
        self.gridLayout_6.addWidget(self.le_pos6_2, 4, 1, 1, 1)
        self.label_136 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_136.setFont(font)
        self.label_136.setObjectName(_fromUtf8("label_136"))
        self.gridLayout_6.addWidget(self.label_136, 4, 2, 1, 1)
        self.label_43 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.gridLayout_6.addWidget(self.label_43, 5, 0, 1, 1)
        self.le_pos7_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos7_2.setFont(font)
        self.le_pos7_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos7_2.setReadOnly(True)
        self.le_pos7_2.setObjectName(_fromUtf8("le_pos7_2"))
        self.gridLayout_6.addWidget(self.le_pos7_2, 5, 1, 1, 1)
        self.label_137 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_137.setFont(font)
        self.label_137.setObjectName(_fromUtf8("label_137"))
        self.gridLayout_6.addWidget(self.label_137, 5, 2, 1, 1)
        self.label_44 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.gridLayout_6.addWidget(self.label_44, 6, 0, 1, 1)
        self.le_pos8_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos8_2.setFont(font)
        self.le_pos8_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos8_2.setReadOnly(True)
        self.le_pos8_2.setObjectName(_fromUtf8("le_pos8_2"))
        self.gridLayout_6.addWidget(self.le_pos8_2, 6, 1, 1, 1)
        self.label_138 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_138.setFont(font)
        self.label_138.setObjectName(_fromUtf8("label_138"))
        self.gridLayout_6.addWidget(self.label_138, 6, 2, 1, 1)
        self.label_45 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.gridLayout_6.addWidget(self.label_45, 7, 0, 1, 1)
        self.le_pos9_2 = QtGui.QLineEdit(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.le_pos9_2.setFont(font)
        self.le_pos9_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.le_pos9_2.setReadOnly(True)
        self.le_pos9_2.setObjectName(_fromUtf8("le_pos9_2"))
        self.gridLayout_6.addWidget(self.le_pos9_2, 7, 1, 1, 1)
        self.label_139 = QtGui.QLabel(self.gb_axisreadings_2)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_139.setFont(font)
        self.label_139.setObjectName(_fromUtf8("label_139"))
        self.gridLayout_6.addWidget(self.label_139, 7, 2, 1, 1)
        self.groupBox_15 = QtGui.QGroupBox(self.tab_measurement)
        self.groupBox_15.setGeometry(QtCore.QRect(10, 328, 990, 540))
        self.groupBox_15.setTitle(_fromUtf8(""))
        self.groupBox_15.setObjectName(_fromUtf8("groupBox_15"))
        self.graphicsView_1 = PlotWidget(self.groupBox_15)
        self.graphicsView_1.setGeometry(QtCore.QRect(10, 10, 971, 520))
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.NoBrush)
        self.graphicsView_1.setBackgroundBrush(brush)
        self.graphicsView_1.setObjectName(_fromUtf8("graphicsView_1"))
        self.tabWidget.addTab(self.tab_measurement, _fromUtf8(""))

        self.retranslateUi(F_Kugler_Bench)
        self.tabWidget.setCurrentIndex(0)
        self.tb_Motors_main.setCurrentIndex(1)
        QtCore.QObject.connect(self.le_pos1, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos1_2.setText)
        QtCore.QObject.connect(self.le_pos2, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos2_2.setText)
        QtCore.QObject.connect(self.le_pos3, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos3_2.setText)
        QtCore.QObject.connect(self.le_pos5, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos5_2.setText)
        QtCore.QObject.connect(self.le_pos6, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos6_2.setText)
        QtCore.QObject.connect(self.le_pos7, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos7_2.setText)
        QtCore.QObject.connect(self.le_pos8, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos8_2.setText)
        QtCore.QObject.connect(self.le_pos9, QtCore.SIGNAL(_fromUtf8("textChanged(QString)")), self.le_pos9_2.setText)
        QtCore.QMetaObject.connectSlotsByName(F_Kugler_Bench)
        F_Kugler_Bench.setTabOrder(self.tabWidget, self.cb_DMM_X)
        F_Kugler_Bench.setTabOrder(self.cb_DMM_X, self.cb_DMM_Y)
        F_Kugler_Bench.setTabOrder(self.cb_DMM_Y, self.sb_DMM_X_address)
        F_Kugler_Bench.setTabOrder(self.sb_DMM_X_address, self.sb_DMM_Y_address)
        F_Kugler_Bench.setTabOrder(self.sb_DMM_Y_address, self.cb_DMM_Z)
        F_Kugler_Bench.setTabOrder(self.cb_DMM_Z, self.sb_DMM_Z_address)
        F_Kugler_Bench.setTabOrder(self.sb_DMM_Z_address, self.cb_PMAC_enable)
        F_Kugler_Bench.setTabOrder(self.cb_PMAC_enable, self.cb_Multichannel_enable)
        F_Kugler_Bench.setTabOrder(self.cb_Multichannel_enable, self.sb_Multichannel_address)
        F_Kugler_Bench.setTabOrder(self.sb_Multichannel_address, self.cb_Autocolimator_enable)
        F_Kugler_Bench.setTabOrder(self.cb_Autocolimator_enable, self.cb_Autocolimator_port)
        F_Kugler_Bench.setTabOrder(self.cb_Autocolimator_port, self.le_filenameconfig)
        F_Kugler_Bench.setTabOrder(self.le_filenameconfig, self.pb_loadconfigfile)
        F_Kugler_Bench.setTabOrder(self.pb_loadconfigfile, self.pb_saveconfigfile)
        F_Kugler_Bench.setTabOrder(self.pb_saveconfigfile, self.pb_connectdevices)
        F_Kugler_Bench.setTabOrder(self.pb_connectdevices, self.pb_disconnectdevices)
        F_Kugler_Bench.setTabOrder(self.pb_disconnectdevices, self.pb_activatebench)
        F_Kugler_Bench.setTabOrder(self.pb_activatebench, self.cb_homming1)
        F_Kugler_Bench.setTabOrder(self.cb_homming1, self.cb_homming2)
        F_Kugler_Bench.setTabOrder(self.cb_homming2, self.cb_homming3)
        F_Kugler_Bench.setTabOrder(self.cb_homming3, self.pb_starthomming)
        F_Kugler_Bench.setTabOrder(self.pb_starthomming, self.cb_homming5)
        F_Kugler_Bench.setTabOrder(self.cb_homming5, self.cb_homming6)
        F_Kugler_Bench.setTabOrder(self.cb_homming6, self.cb_homming7)
        F_Kugler_Bench.setTabOrder(self.cb_homming7, self.cb_homming8)
        F_Kugler_Bench.setTabOrder(self.cb_homming8, self.cb_homming9)
        F_Kugler_Bench.setTabOrder(self.cb_homming9, self.le_velocity)
        F_Kugler_Bench.setTabOrder(self.le_velocity, self.cb_selectaxis)
        F_Kugler_Bench.setTabOrder(self.cb_selectaxis, self.le_targetposition)
        F_Kugler_Bench.setTabOrder(self.le_targetposition, self.pb_movetotarget)
        F_Kugler_Bench.setTabOrder(self.pb_movetotarget, self.pb_stopmotor)
        F_Kugler_Bench.setTabOrder(self.pb_stopmotor, self.pb_stopallmotors)
        F_Kugler_Bench.setTabOrder(self.pb_stopallmotors, self.pb_killallmotors)
        F_Kugler_Bench.setTabOrder(self.pb_killallmotors, self.le_pos1)
        F_Kugler_Bench.setTabOrder(self.le_pos1, self.le_pos2)
        F_Kugler_Bench.setTabOrder(self.le_pos2, self.le_pos3)
        F_Kugler_Bench.setTabOrder(self.le_pos3, self.le_pos5)
        F_Kugler_Bench.setTabOrder(self.le_pos5, self.le_pos6)
        F_Kugler_Bench.setTabOrder(self.le_pos6, self.le_pos7)
        F_Kugler_Bench.setTabOrder(self.le_pos7, self.le_pos8)
        F_Kugler_Bench.setTabOrder(self.le_pos8, self.le_pos9)
        F_Kugler_Bench.setTabOrder(self.le_pos9, self.cb_Hall_X_enable)
        F_Kugler_Bench.setTabOrder(self.cb_Hall_X_enable, self.cb_Hall_Y_enable)
        F_Kugler_Bench.setTabOrder(self.cb_Hall_Y_enable, self.cb_Hall_Z_enable)
        F_Kugler_Bench.setTabOrder(self.cb_Hall_Z_enable, self.le_DMM_aper)
        F_Kugler_Bench.setTabOrder(self.le_DMM_aper, self.cb_DMM_precision)
        F_Kugler_Bench.setTabOrder(self.cb_DMM_precision, self.le_filenamemeasurement)
        F_Kugler_Bench.setTabOrder(self.le_filenamemeasurement, self.pb_loadmeasurementfile)
        F_Kugler_Bench.setTabOrder(self.pb_loadmeasurementfile, self.pb_savemeasurementfile)
        F_Kugler_Bench.setTabOrder(self.pb_savemeasurementfile, self.rb_triggering_axis1)
        F_Kugler_Bench.setTabOrder(self.rb_triggering_axis1, self.le_axis1_start)
        F_Kugler_Bench.setTabOrder(self.le_axis1_start, self.le_axis1_end)
        F_Kugler_Bench.setTabOrder(self.le_axis1_end, self.le_axis1_step)
        F_Kugler_Bench.setTabOrder(self.le_axis1_step, self.le_axis1_vel)
        F_Kugler_Bench.setTabOrder(self.le_axis1_vel, self.rb_triggering_axis2)
        F_Kugler_Bench.setTabOrder(self.rb_triggering_axis2, self.le_axis2_start)
        F_Kugler_Bench.setTabOrder(self.le_axis2_start, self.le_axis2_end)
        F_Kugler_Bench.setTabOrder(self.le_axis2_end, self.le_axis2_step)
        F_Kugler_Bench.setTabOrder(self.le_axis2_step, self.le_axis2_vel)
        F_Kugler_Bench.setTabOrder(self.le_axis2_vel, self.rb_triggering_axis3)
        F_Kugler_Bench.setTabOrder(self.rb_triggering_axis3, self.le_axis3_start)
        F_Kugler_Bench.setTabOrder(self.le_axis3_start, self.le_axis3_end)
        F_Kugler_Bench.setTabOrder(self.le_axis3_end, self.le_axis3_step)
        F_Kugler_Bench.setTabOrder(self.le_axis3_step, self.le_axis3_vel)
        F_Kugler_Bench.setTabOrder(self.le_axis3_vel, self.le_axis5_start)
        F_Kugler_Bench.setTabOrder(self.le_axis5_start, self.le_axis5_end)
        F_Kugler_Bench.setTabOrder(self.le_axis5_end, self.le_axis5_step)
        F_Kugler_Bench.setTabOrder(self.le_axis5_step, self.le_axis5_vel)

    def retranslateUi(self, F_Kugler_Bench):
        F_Kugler_Bench.setWindowTitle(_translate("F_Kugler_Bench", "Magnetic Measurement System Software", None))
        self.label_128.setText(_translate("F_Kugler_Bench", "Digital Multimeters\n"
"(Hall Probes)", None))
        self.cb_DMM_X.setText(_translate("F_Kugler_Bench", "X-axis", None))
        self.cb_DMM_Y.setText(_translate("F_Kugler_Bench", "Y-axis", None))
        self.cb_DMM_Z.setText(_translate("F_Kugler_Bench", "Z-axis", None))
        self.label_130.setText(_translate("F_Kugler_Bench", "PMAC\n"
"(Delta Tau)", None))
        self.cb_PMAC_enable.setText(_translate("F_Kugler_Bench", "Enable connection", None))
        self.label_129.setText(_translate("F_Kugler_Bench", "Digital Multichannel\n"
"(Temperatures)", None))
        self.cb_Multichannel_enable.setText(_translate("F_Kugler_Bench", "Enable", None))
        self.label_131.setText(_translate("F_Kugler_Bench", "Auto-Colimator", None))
        self.cb_Autocolimator_port.setItemText(0, _translate("F_Kugler_Bench", "COM 1", None))
        self.cb_Autocolimator_port.setItemText(1, _translate("F_Kugler_Bench", "COM 2", None))
        self.cb_Autocolimator_port.setItemText(2, _translate("F_Kugler_Bench", "COM 3", None))
        self.cb_Autocolimator_port.setItemText(3, _translate("F_Kugler_Bench", "COM 4", None))
        self.cb_Autocolimator_port.setItemText(4, _translate("F_Kugler_Bench", "COM 5", None))
        self.cb_Autocolimator_port.setItemText(5, _translate("F_Kugler_Bench", "COM 6", None))
        self.cb_Autocolimator_port.setItemText(6, _translate("F_Kugler_Bench", "COM 7", None))
        self.cb_Autocolimator_port.setItemText(7, _translate("F_Kugler_Bench", "COM 8", None))
        self.cb_Autocolimator_port.setItemText(8, _translate("F_Kugler_Bench", "COM 9", None))
        self.cb_Autocolimator_port.setItemText(9, _translate("F_Kugler_Bench", "COM 10", None))
        self.cb_Autocolimator_port.setItemText(10, _translate("F_Kugler_Bench", "COM 11", None))
        self.cb_Autocolimator_port.setItemText(11, _translate("F_Kugler_Bench", "COM 12", None))
        self.cb_Autocolimator_port.setItemText(12, _translate("F_Kugler_Bench", "COM 13", None))
        self.cb_Autocolimator_port.setItemText(13, _translate("F_Kugler_Bench", "COM 14", None))
        self.cb_Autocolimator_port.setItemText(14, _translate("F_Kugler_Bench", "COM 15", None))
        self.cb_Autocolimator_enable.setText(_translate("F_Kugler_Bench", "Enable", None))
        self.groupBox_7.setTitle(_translate("F_Kugler_Bench", "Configuration File", None))
        self.label_3.setText(_translate("F_Kugler_Bench", "Filename: ", None))
        self.pb_saveconfigfile.setText(_translate("F_Kugler_Bench", "Save File", None))
        self.pb_loadconfigfile.setText(_translate("F_Kugler_Bench", "Load File", None))
        self.pb_connectdevices.setText(_translate("F_Kugler_Bench", "Connect Devices", None))
        self.pb_disconnectdevices.setText(_translate("F_Kugler_Bench", "Disconnect Devices", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("F_Kugler_Bench", "Connection", None))
        self.label_23.setText(_translate("F_Kugler_Bench", "#1 (+Z):", None))
        self.le_pos1.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_120.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_24.setText(_translate("F_Kugler_Bench", "#2 (+Y):", None))
        self.le_pos2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_121.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_25.setText(_translate("F_Kugler_Bench", "#3 (+X):", None))
        self.le_pos3.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_122.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_26.setText(_translate("F_Kugler_Bench", "#5 (+A):", None))
        self.le_pos5.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_123.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_27.setText(_translate("F_Kugler_Bench", "#6 (+W):", None))
        self.le_pos6.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_124.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_28.setText(_translate("F_Kugler_Bench", "#7 (+V):", None))
        self.le_pos7.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_125.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_29.setText(_translate("F_Kugler_Bench", "#8 (+B):", None))
        self.le_pos8.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_126.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_30.setText(_translate("F_Kugler_Bench", "#9 (+C):", None))
        self.le_pos9.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_127.setText(_translate("F_Kugler_Bench", "mm", None))
        self.groupBox_9.setTitle(_translate("F_Kugler_Bench", "Select axis for homming:", None))
        self.pb_starthomming.setText(_translate("F_Kugler_Bench", "Start Homming", None))
        self.cb_homming1.setText(_translate("F_Kugler_Bench", "#1 (+Z)", None))
        self.cb_homming5.setText(_translate("F_Kugler_Bench", "#5 (+A)", None))
        self.cb_homming8.setText(_translate("F_Kugler_Bench", "#8 (+B)", None))
        self.cb_homming2.setText(_translate("F_Kugler_Bench", "#2 (+Y)", None))
        self.cb_homming6.setText(_translate("F_Kugler_Bench", "#6 (+W)", None))
        self.cb_homming9.setText(_translate("F_Kugler_Bench", "#9 (+C)", None))
        self.cb_homming3.setText(_translate("F_Kugler_Bench", "#3 (+X)", None))
        self.cb_homming7.setText(_translate("F_Kugler_Bench", "#7 (+V)", None))
        self.tb_Motors_main.setItemText(self.tb_Motors_main.indexOf(self.tbmotors_homming), _translate("F_Kugler_Bench", "Homming", None))
        self.label_21.setText(_translate("F_Kugler_Bench", "Velocity [unit/s]:", None))
        self.le_velocity.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_2.setText(_translate("F_Kugler_Bench", "Axis:", None))
        self.cb_selectaxis.setItemText(0, _translate("F_Kugler_Bench", "#1 (+Z & Z\') [mm]", None))
        self.cb_selectaxis.setItemText(1, _translate("F_Kugler_Bench", "#2 (+Y) [mm]", None))
        self.cb_selectaxis.setItemText(2, _translate("F_Kugler_Bench", "#3 (+X) [mm]", None))
        self.cb_selectaxis.setItemText(3, _translate("F_Kugler_Bench", "#5 (+A) [deg]", None))
        self.cb_selectaxis.setItemText(4, _translate("F_Kugler_Bench", "#6 (+W) [mm]", None))
        self.cb_selectaxis.setItemText(5, _translate("F_Kugler_Bench", "#7 (+V) [mm]", None))
        self.cb_selectaxis.setItemText(6, _translate("F_Kugler_Bench", "#8 (+B) [deg]", None))
        self.cb_selectaxis.setItemText(7, _translate("F_Kugler_Bench", "#9 (+C) [deg]", None))
        self.label_20.setText(_translate("F_Kugler_Bench", "Target Position [unit]:", None))
        self.le_targetposition.setText(_translate("F_Kugler_Bench", "0.0000", None))
        self.pb_stopmotor.setText(_translate("F_Kugler_Bench", "Stop Motor", None))
        self.pb_movetotarget.setText(_translate("F_Kugler_Bench", "Move to Target", None))
        self.tb_Motors_main.setItemText(self.tb_Motors_main.indexOf(self.tbmotors_movements), _translate("F_Kugler_Bench", "Movements", None))
        self.pb_killallmotors.setText(_translate("F_Kugler_Bench", "Kill All Motors", None))
        self.pb_stopallmotors.setText(_translate("F_Kugler_Bench", "Stop All Motors", None))
        self.pb_activatebench.setText(_translate("F_Kugler_Bench", "Activate Bench", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_motors), _translate("F_Kugler_Bench", "Motors", None))
        self.groupBox_10.setTitle(_translate("F_Kugler_Bench", "Hall probes", None))
        self.cb_Hall_X_enable.setText(_translate("F_Kugler_Bench", "X-axis", None))
        self.cb_Hall_Y_enable.setText(_translate("F_Kugler_Bench", "Y-axis", None))
        self.cb_Hall_Z_enable.setText(_translate("F_Kugler_Bench", "Z-axis", None))
        self.groupBox_11.setTitle(_translate("F_Kugler_Bench", "Digital Multimeter Parameters", None))
        self.label_22.setText(_translate("F_Kugler_Bench", "Aperture Time [s]:", None))
        self.le_DMM_aper.setText(_translate("F_Kugler_Bench", "0.003", None))
        self.cb_DMM_precision.setItemText(0, _translate("F_Kugler_Bench", "Single", None))
        self.cb_DMM_precision.setItemText(1, _translate("F_Kugler_Bench", "Double", None))
        self.label_32.setText(_translate("F_Kugler_Bench", "Memory Precision :", None))
        self.groupBox_12.setTitle(_translate("F_Kugler_Bench", "Positions", None))
        self.label_35.setText(_translate("F_Kugler_Bench", "#2 (+Y) [mm]:", None))
        self.label_16.setText(_translate("F_Kugler_Bench", "Start", None))
        self.label_40.setText(_translate("F_Kugler_Bench", "#1 (+Z) [mm]:", None))
        self.label_17.setText(_translate("F_Kugler_Bench", "End", None))
        self.label_15.setText(_translate("F_Kugler_Bench", "Step", None))
        self.label_36.setText(_translate("F_Kugler_Bench", "#5 (+A) [deg]:", None))
        self.label_39.setText(_translate("F_Kugler_Bench", "#3 (+X) [mm]:", None))
        self.label_19.setText(_translate("F_Kugler_Bench", "Velocity [unit/s]", None))
        self.label_18.setText(_translate("F_Kugler_Bench", "Axis", None))
        self.groupBox_13.setTitle(_translate("F_Kugler_Bench", "Load / Save", None))
        self.pb_savemeasurementfile.setText(_translate("F_Kugler_Bench", "Save File", None))
        self.pb_loadmeasurementfile.setText(_translate("F_Kugler_Bench", "Load File", None))
        self.label_9.setText(_translate("F_Kugler_Bench", "Filename: ", None))
        self.groupBox_14.setTitle(_translate("F_Kugler_Bench", "Configure and Measure", None))
        self.pb_configure_measurement.setText(_translate("F_Kugler_Bench", "Configure and Measure", None))
        self.pb_stop_measurements.setText(_translate("F_Kugler_Bench", "Stop Measurements", None))
        self.label_33.setText(_translate("F_Kugler_Bench", "# of Measurements:", None))
        self.l_n_meas_status.setText(_translate("F_Kugler_Bench", "1", None))
        self.label_34.setText(_translate("F_Kugler_Bench", "#1 (+Z):", None))
        self.le_pos1_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_132.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_37.setText(_translate("F_Kugler_Bench", "#2 (+Y):", None))
        self.le_pos2_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_133.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_38.setText(_translate("F_Kugler_Bench", "#3 (+X):", None))
        self.le_pos3_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_134.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_41.setText(_translate("F_Kugler_Bench", "#5 (+A):", None))
        self.le_pos5_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_135.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_42.setText(_translate("F_Kugler_Bench", "#6 (+W):", None))
        self.le_pos6_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_136.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_43.setText(_translate("F_Kugler_Bench", "#7 (+V):", None))
        self.le_pos7_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_137.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_44.setText(_translate("F_Kugler_Bench", "#8 (+B):", None))
        self.le_pos8_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_138.setText(_translate("F_Kugler_Bench", "mm", None))
        self.label_45.setText(_translate("F_Kugler_Bench", "#9 (+C):", None))
        self.le_pos9_2.setText(_translate("F_Kugler_Bench", "0.00", None))
        self.label_139.setText(_translate("F_Kugler_Bench", "mm", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_measurement), _translate("F_Kugler_Bench", "Measurements", None))

from pyqtgraph import PlotWidget
import resource_file_rc
